server.port=8085
spring.application.name=mining-accident-service
dpdms.hazard-type=MINING_ACCIDENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
